### ISSUE TITLE
Fehler in der Drucker-Testseite

### ISSUE THREAD

**Issue by EugenVau** [sidiandi/ttaudio#14]
Im Quelltext der Drucker-Testseite haben sich ein paar Fehler eingeschlichen:

1. Komma statt Punkt als Dezimal-Trennzeichen bei den SVGs, z.B.:
ist 
`<circle cx="0,0015625cm" cy="0,0015625cm" r="0,000625cm" style="stroke: none; fill: #000000;"/>
`
soll 
`<circle cx="0.0015625cm" cy="0.0015625cm" r="0.000625cm" style="stroke: none; fill: #000000;"/>
`

2. Ein Bild wird an der falschen Stelle gesucht (oder fehlt an der richtigen Stelle):
`<img src="media/note_to_pen.png" />` 
der Ordner "media" wird gesucht in "%USERPROFILE%/AppData/Local/sidiandi/ttaudio/", ist aber dort nicht vorhanden.

**Comment by EugenVau** [comment]
Danke für den schnellen Fix! :-)

Der 2. Fehler (das nicht gefundene Bild) ist aber immer noch da...

**Comment by sidiandi** [comment]
2. Fehler ist noch nicht behoben.
