### ISSUE TITLE
Bug "Save as..." and "Save"

### ISSUE THREAD

**Issue by ifb-mk** [sidiandi/ttaudio#15]
I opened "Save as..." unintentionally but I can´t get back.
The window pops up after choosing "Cancel".
Same issue when choosing "Save".
Had to stop the process with Taskmanager.

**Comment by sidiandi** [comment]
Thanks!

 

https://github.com/sidiandi/ttaudio/releases/tag/v0.7.2

**Comment by ifb-mk** [comment]
Hi,

I´ve tested the new release but the issue is not fixed.
