### ISSUE TITLE
Probleme beim Installieren

### ISSUE THREAD

**Issue by sixpak** [sidiandi/ttaudio#17]
moin ...
... mir ist noch nicht schlüssig, wie das Tool installiert wird.
Die MSI habe ich ... aber es startet kurz und das war's dann ...
Habe ich einen Denkfehler?

greetz

**Comment by sidiandi** [comment]
Hallo sixpak,

 

Wenn das MSI gelaufen ist, sollte ttaudio installiert sein. Es gibt dann im Startmenu ein „ttaudio“ Icon. Auf das musst Du klicken, um das Programm zu starten. Falls Du es dort nicht finden kannst, kannst Du das Programm mit 

 

"%ProgramFiles(X86)%\sidiandi\ttaudio\ttaudio.exe" 

 

auch direkt starten.

 

Freundliche Grüße,

 

sidiandi

**Comment by sixpak** [comment]
Also gebaut hat ttaudio irgendwas ;)
Die Seite habe ich ausgedruckt ... mehrfach ...
Auf normalen, hochauflösenden und Fotopapier ...
Aber das Hörbuch lässt sich nicht aktivieren

**Comment by sidiandi** [comment]
Welchen Drucker verwendest Du?

Freundliche Grüße,

Andreas

**Comment by sixpak** [comment]
Aktuell einen Tintenstrahler ...
Canon MX885
9600x2400 dpi im Fotomodus ...

greetz

Der Rico

**Comment by sidiandi** [comment]
Hallo Rico,

 

die Auflösung sollte reichen. Schau Dir mal die Tipps auf

 

http://tttool.entropia.de/#produkt-drucken

 

an. Du kannst mir auch ein Handyfoto vom Ausdruck schicken (so nahe rangehen, dass das Bild gerade noch scharf ist). Vielleicht kann ich was erkennen.

 

Freundliche Grüße,

 

Andreas

**Comment by anne-fr** [comment]
Hallo,
ich weiß nicht, wie ich das Programm installieren soll. Wo ist denn die msi oder setup-Datei?
Danke,
Anne

**Comment by Kaja-g** [comment]
Hallo zusammen,
ich wollte gerne ein paar MP3 auf den tiptoi Stift laden. Aber ich komme leider mit der Anleitung / Installation nicht ganz zurecht. Wo kann ich mir das Program ttaudio runterladen? 
Vielen Dank und schöne Grüße Kathi

**Comment by sidiandi** [comment]
I have added installation instructions to the Readme.md page
