### ISSUE TITLE
Wie kann ich dieses Programm nutzen?

### ISSUE THREAD

**Issue by M1r0o** [sidiandi/ttaudio#18]
Hallo,
ich schaffe es nicht, dieses Programm zum Laufen zu bekommen!
Kann mir jemand ein kurzes HowTo posten, wie es zu installieren ist - ich raffe es nicht!?

**Comment by sidiandi** [comment]
den MSI installer auf github unter "Releases" runterladen und installieren. dann über das Startmenü ttaudio starten.

Freundliche Grüße,

Andreas

**Comment by M1r0o** [comment]
Vielen Dank für die Antwort, aber ich kann es gar nicht installieren, da ich keine ausführbare Datei (exe) finde.

**Comment by sidiandi** [comment]
Hallo,

bitte von

https://github.com/sidiandi/ttaudio/releases/latest

das *.msi file runterladen und doppelklicken.

Freundliche Grüße,

Andreas

**Comment by M1r0o** [comment]
Sehr gut, vielen Dank! Ich hatte bisher nur die Einzeldateien entdeckt.
