### ISSUE TITLE
Probleme beim Kombilieren VS 2012

### ISSUE THREAD

**Issue by rolandabt** [sidiandi/ttaudio#19]
Hallo

Ich wollte gerade die Source unter VS 2012 kompilieren. Dabei erscheint eine Fehlermeldung, dass "Auth.targets" nicht zu finden ist. Ist das nur bei neueren VS Versionen vorhanden oder hast du vergessen, diese Datei einzuchecken?

Gruss
Roland

**Comment by sidiandi** [comment]
Hallo,

 

wenn Du nur die Binaries brauchst, kannst Du die unter

 

https://github.com/sidiandi/ttaudio/releases/latest

 

runterladen. Wenn Du ttaudio wirklich selber kompilieren möchtest, solltest Du das neueste Visual Studio verwenden. Gibt’s als Express Variante auch umsonst.

 

Die Fehlermeldung deutet darauf hin, dass Du eine ältere msbuild Version verwendest.

 

Freundliche Grüße,

 

Andreas

**Comment by FatBastard79** [comment]
Hallo Andreas,

das hat nichts mit der Version des VS zu tun. 
In den von dir bereitgestellten Sourcen fehlt einfach die "Auth.targets" Datei.
Was verständlich ist, da darin dein GitHub API Key enthalten ist, mit der du automatisch hier in das GIT Repo auf GitHub einchecken kannst...
Da du dir das alles automatisiert hast und nur die build.bat aufrufen musst und du die Datei auf deinem Rechner hast, hast du vermutlich nicht bemerkt, dass in der Datei "build.props" ein direkter import auf die Auth.targets gemacht wird. Wenn diese fehlt, kann man die Solution nicht in VS öffnen.

Abhilfe schaft, die Zeile 
<Import Project="Auth.targets"  />
in der build.props aus zu kommentieren, also
	

Generell kannst du ja einen Weiche in die MSBuild Scripte einbauen, dass er nicht immer versucht die nicht vorhandene Datei zu importieren :)

Bye
Clemens

**Comment by sidiandi** [comment]
I have setup a continuous integration build with gocd to avoid missing files in future. And I have added a "How to Compile" section in the readme.
