### ISSUE TITLE
Printer Test Page

### ISSUE THREAD

**Issue by MJoaoA** [sidiandi/ttaudio#20]
Hallo,

wofür genau ist die Seite "Printer test Page"? Ich habe die Seite getestet und festgestellt, dass bei mir die Reihe "Grid Spacing 0,0138 cm" vom Stift erkannt wird. Was kann ich mit dieser Info machen? Das drucken vom html hat bei mir nicht funktioniert. Ich habe die verschiedene Layouts und verschiedene Kontrast- und Helligkeitseinstellungen ausprobiert alles bei 1200 dpi und nichts. Die Test Seite funkt aber. Muss ich das html skalieren?

Danke für deine Arbeit!

MFG Joao

**Comment by sidiandi** [comment]
> %LOCALAPPDATA%\sidiandi\ttaudio\ttaudio.settings.xml

> Sorry, es gibt noch kein "Settings" User Interface. Das muss ich bei
> Gelegenheit noch fertigstellen.

Freundliche Grüße,

Andreas

**Comment by MJoaoA** [comment]
Hi,
Ich habe bei mir nur eine ttaudio.xml und eine ttaenc.xml. In der ttaenc.xml siehe ich das Dot size und grid size von irgend ein Befehl oder Datei mit dem Name *OidSvgWriter* kommt (soweit ich es verstehe, bin keine Expertin):
"
-<member name="P:ttaenc.OidSvgWriter.DotSize">
<summary> Dot size in cm </summary>
</member>
-<member name="P:ttaenc.OidSvgWriter.DotOffset">
<summary> Dot bit offset in cm </summary>
</member>
-<member name="P:ttaenc.OidSvgWriter.GridSpacing2">
<summary> Double of grid spacing in cm </summary>
</member>
-<member name="P:ttaenc.OidSvgWriter.GridSpacing">
<summary> Grid spacing in cm </summary>" 

Man kann aber hier keine Werte ändern. 
ttaudio.settings.xml direkt gibt es bei mir nicht.

Sorry, habe noch nicht so richtig kapiert wie dass mit dem OIDs funktioniert. Die selbe OIDs sehen z.B. für die selbe gme anders auch je nach Layout????
MFG Joao

**Comment by sidiandi** [comment]
Das muss ich mir mal zuhause ansehen, ab 30.5. Bin gerade im Urlaub.

Freundliche Grüße,

Andreas

**Comment by Pielo84** [comment]
Gibt es die Test-Page noch irgendwo? Kann sie irgendwie nicht im Verzeichnis finden :-(

lg Pielo84

**Comment by sidiandi** [comment]
How to show the printer test page:
* start ttaudio
* In the main menu, select *Tools => Printer Test Page...*
* The printer test page will show up in a new browser window

**Comment by sidiandi** [comment]
Printer test page is now accessible via *Tools => Printer Test Page*. I have also added instructions on how to enter the optimal grid spacing and dot size values.
