### ISSUE TITLE
OID änder bei der HTML Druchseite

### ISSUE THREAD

**Issue by ssteff29** [sidiandi/ttaudio#26]
Hallo,

mein Sohn hat jetzt auch so einen Stift bekommen und natürlich wollte ich gleich ttaudio ausprobieren was super funktioniert mit dem Draufladen
Danke dafür

Aber der Stift kann die OID nicht lesen.
Mit der Printer Test Seite habe ich jetzt einen OID gefunden der funktioniert mit meinem Drucker
Ich will mir keinen neuen Drucker kaufen.

DOT Size 0,0038 cm
Grid Spacing 0,0166 cm

Gibt es ne möglichkeit das irgendwo umzustellen oder das man eine Version mit diesen Einstellungen neu kompiliert.

Bitte um Antwort
Danke

**Comment by Tronje-the-Falconer** [comment]
Die Conig-Datei findet man versteckt unter
C:\Users\BENUTZERNAMe\AppData\Local\sidiandi\ttaudio\ttaudio.settings.xml

Hier gibt es die Parameter: OidDotSize und OidGridSpacing

**Comment by sidiandi** [comment]
With [release 0.16.0](https://github.com/sidiandi/ttaudio/releases/tag/v0.16.0), you can adjust these values in 

*Main menu => Tools => Options*
