### ISSUE TITLE
Playback Mode does not seem to work

### ISSUE THREAD

**Issue by Lusor666** [sidiandi/ttaudio#32]
When setting the playback mode to "Stop after everything" still the next song plays after the last is finshed.

**Comment by sidiandi** [comment]
Cannot reproduce. "Stop after everything" means that all albums play in order and playback stops after the last song of the last album.

Could you please attach a *.tta file which reproduces the issue?

**Comment by Lusor666** [comment]
My bad. I interpreted "stop after everything" as stop after each track. When oping the dropdown everything is clear. Perhaps naming this "stop at end" would clearify.

**Comment by sidiandi** [comment]
Option is now named "Stop after everything" to distinguish from other options "Stop after every track" and "Stop after every album"
