### ISSUE TITLE
When no TipToi is attached the tool does not output the gme-file

### ISSUE THREAD

**Issue by Lusor666** [sidiandi/ttaudio#33]
It would be great if you could choose the path for the GME file or at least if an error is displayed if no Tiptoi is attached.

**Comment by sidiandi** [comment]
When upload fails, ttaudio will inform the user now and the generated output will be displayed in an Explorer window for later reference.

Further, I have improved the directory structure and naming of the output files.

**Comment by sidiandi** [comment]
Solved in release

https://github.com/sidiandi/ttaudio/releases/tag/v0.16.0
