### ISSUE TITLE
Release as ZIP file, don't install to a fixed dir without asking

### ISSUE THREAD

**Issue by SciLor** [sidiandi/ttaudio#36]
"C:\Program Files (x86)\sidiandi" is fixed and the program is installed without any dialog or were it is installed.

**Comment by sidiandi** [comment]
Good point. I'll supply a zip file release and add a directory prompt to the msi as soon as I have time.

**Comment by sidiandi** [comment]
Fixed with [release 0.20.0](https://github.com/sidiandi/ttaudio/releases/tag/v0.20.0)
