### ISSUE TITLE
Feedback - 

### ISSUE THREAD

**Issue by Jixxi** [sidiandi/ttaudio#8]
Hallo, 

vorab: ein tolles Projekt, genau was ich Suche ;) 

Ich habe das Prerelease 0.1.9 geladen und auf einem Windows 10 installiert. Die Installation lief reibungslos und auch das Programm tat was es sollte. Heißt: Ich habe die *.gme auf dem Stick und die OIDs werden auch erstellt. 

Beim Test musste ich feststellen, das der Stift gar nichts damit tun will. also nicht reagiert. 

Es handelt sich um den neuen Stift mit Player. Im Anhang eine Test gme mit einem Lied und das entsprechende pdf dazu. Drucker ist ein Samsung SCX 4623
[test.pdf](https://github.com/sidiandi/ttaudio/files/102929/test.pdf)

[test.zip](https://github.com/sidiandi/ttaudio/files/102931/test.zip)

**Comment by sidiandi** [comment]
Hallo Jixxi,

danke für das Testen von ttaudio. Ich habe mir gerade die Dateien angesehen und auf meinem [Samsung SCX 4500]( http://www.samsung.com/de/support/model/SCX-4500/SEE) ausgedruckt.

Das Fazit:
* test.pdf – geht nicht. Man sieht auch ganz deutlich, dass PDF-Drucker-Treiber die OIDs durch sehr grob gerasterte Bitmaps ersetzt hat.
* test.html – geht.

Dein [SCX-4623](http://www.samsung.com/us/computer/printers/SCX-4623F/XAA-specs) sollte eigentlich gut genug sein. Noch ein paar Tipps zum Troubleshooting:
-	Druckereinstellungen kontrollieren (Toner-Spar-Modus, „eco-mode“ oder ähnliches muss aus sein)
-	Direkt von der HTML Seite drucken, nicht den Umweg über PDF gehen – aber das hast Du wahrscheinlich sowieso schon gemacht.

Wenn Du nicht weiterkommst, kannst Du mir auch einen Probeausdruck per normaler Post schicken. [Addresse gibt es hier]( http://safemail.justlikeed.net/e/a59892f3fcf89e70f47cfa22056db7ca.png)

**Comment by Jixxi** [comment]
Hallo,

Vielen Dank für das schnelle Feedback, ich spiele heute nochmal mit den
Druckereinstellungen rum. Jetzt weiß ich ja das es prinzipiell gehen muss.

Liebe Grüße, Susanne
Am 26.01.2016 05:26 schrieb "sidiandi" <notifications@github.com>:

**Comment by Jixxi** [comment]
Hallo,

Es hat funktioniert. Danke nochmal. Hier noch einige Anmerkungen:

Für kleine Kinder sind die Codes schwer zu treffen, eventuell wäre eine
Ansicht mit größeren Codes da sinnvoll, (eventuell mit Platz das man Bilder
dahinter machen kann).
Ausserdem wäre für kleine Kinder ein Start und Stop Zeichen vielleicht
sinnvoll.

Liebe Grüße,
Susanne


Am 26. Januar 2016 um 05:34 schrieb Susanne Schubert <
susanne.breitschuh@gmail.com>:

> Hallo,
>
> Vielen Dank für das schnelle Feedback, ich spiele heute nochmal mit den
> Druckereinstellungen rum. Jetzt weiß ich ja das es prinzipiell gehen muss.
>
> Liebe Grüße, Susanne
> Am 26.01.2016 05:26 schrieb "sidiandi" <notifications@github.com>:
>
>> Hallo Jixxi,
>>
>> danke für das Testen von ttaudio. Ich habe mir gerade die Dateien
>> angesehen und auf meinem Samsung SCX 4500
>> <http://www.samsung.com/de/support/model/SCX-4500/SEE> ausgedruckt.
>>
>> Das Fazit:
>>
>>    - test.pdf – geht nicht. Man sieht auch ganz deutlich, dass
>>    PDF-Drucker-Treiber die OIDs durch sehr grob gerasterte Bitmaps ersetzt hat.
>>    - test.html – geht.
>>
>> Dein SCX-4623
>> <http://www.samsung.com/us/computer/printers/SCX-4623F/XAA-specs> sollte
>> eigentlich gut genug sein. Noch ein paar Tipps zum Troubleshooting:
>>
>>    - Druckereinstellungen kontrollieren (Toner-Spar-Modus, „eco-mode“
>>    oder ähnliches muss aus sein)
>>    - Direkt von der HTML Seite drucken, nicht den Umweg über PDF gehen –
>>    aber das hast Du wahrscheinlich sowieso schon gemacht.
>>
>> Wenn Du nicht weiterkommst, kannst Du mir auch einen Probeausdruck per
>> normaler Post schicken. Addresse gibt es hier
>> <http://safemail.justlikeed.net/e/a59892f3fcf89e70f47cfa22056db7ca.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sidiandi/ttaudio/issues/8#issuecomment-174817066>.
>>
>


-- 
Liebe Grüße,
Susanne Breitschuh

mail: susanne.breitschuh@gmail.com
fon: +49 (0) 151 580 566 04
xing: https://www.xing.com/profile/Susanne_Breitschuh2
skype: jixxithecat
msn: zuzi_inc@web.de

**Comment by sidiandi** [comment]
Created #13 for the feature requests from last note.
